name: "Pipe"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
  
      - name: Runner Tests
        run: newman run /postman/test.json -e /postman/env.json