name: "Pipe"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: ./postman/tests.json
          environment: 15370526-a1ec5409-aab9-4301-895e-1a8da5145338
