name: "Pipe"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: install newman
        run: npm install -g newman
  
      - name: Runner Tests
        run: newman run tests.json -e env.json