name: "Pipe"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: install newman
        run: npm install -g newman
  
      - name: Runner Tests with report
        run: newman run tests.json -e env.json -g htmlextra

      - name: Deploy to GitHub Pages
        if: always()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: ./newman
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}